# Generated by Django 3.2.12 on 2022-02-15 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目录名')),
                ('discription', models.CharField(max_length=500, verbose_name='目录描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamecategory', verbose_name='上级目录')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('cover_file_name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('restriction', models.CharField(max_length=500)),
                ('note', models.CharField(max_length=500)),
                ('game_cate', models.IntegerField()),
                ('card_count', models.IntegerField()),
                ('card_name_field', models.CharField(max_length=100)),
                ('card_discriptioin_field', models.CharField(max_length=100)),
                ('card_restriction_field', models.CharField(max_length=100)),
                ('card_note_field', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gamecategory')),
            ],
        ),
    ]
