# Generated by Django 3.2.12 on 2022-03-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_cate',
        ),
        migrations.AddField(
            model_name='game',
            name='xfile',
            field=models.FileField(null=True, upload_to='', verbose_name='数据文件'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.gamecategory', verbose_name='所属目录'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, verbose_name='游戏卡名称'),
        ),
        migrations.AlterField(
            model_name='game',
            name='table_name',
            field=models.CharField(max_length=100, verbose_name='数据表名称'),
        ),
    ]
