# Generated by Django 3.2.12 on 2022-03-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20220301_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover_file_name',
        ),
        migrations.AddField(
            model_name='game',
            name='cfile',
            field=models.FileField(null=True, upload_to='', verbose_name='卡片封面图片'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_count',
            field=models.IntegerField(verbose_name='游戏卡数量'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_discriptioin_field',
            field=models.CharField(max_length=100, verbose_name='卡片描述字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_name_field',
            field=models.CharField(max_length=100, verbose_name='卡片名称字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_note_field',
            field=models.CharField(max_length=100, verbose_name='卡片说明字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_restriction_field',
            field=models.CharField(max_length=100, verbose_name='卡片限制字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='discription',
            field=models.CharField(max_length=500, verbose_name='游戏卡描述'),
        ),
        migrations.AlterField(
            model_name='game',
            name='note',
            field=models.CharField(max_length=500, verbose_name='对游戏卡的其他说明'),
        ),
        migrations.AlterField(
            model_name='game',
            name='restriction',
            field=models.CharField(max_length=500, verbose_name='卡片内容限制'),
        ),
        migrations.AlterField(
            model_name='game',
            name='table_name',
            field=models.CharField(max_length=100, verbose_name='游戏卡的库表名称'),
        ),
        migrations.AlterField(
            model_name='game',
            name='xfile',
            field=models.FileField(null=True, upload_to='', verbose_name='游戏卡数据文件'),
        ),
    ]
