# Generated by Django 3.2.12 on 2022-03-03 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220301_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='table_name',
        ),
        migrations.AlterField(
            model_name='game',
            name='card_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='游戏卡数量'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_discriptioin_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='卡片描述字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_name_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='卡片名称字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_note_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='卡片说明字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='card_restriction_field',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='卡片限制字段'),
        ),
        migrations.AlterField(
            model_name='game',
            name='cfile',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='game',
            name='discription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='游戏描述'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='游戏名称'),
        ),
        migrations.AlterField(
            model_name='game',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='对游戏的其他说明'),
        ),
        migrations.AlterField(
            model_name='game',
            name='restriction',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='游戏限制'),
        ),
        migrations.AlterField(
            model_name='game',
            name='xfile',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='游戏卡数据文件'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='discription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='目录描述'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='目录名'),
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='卡名称')),
                ('discription', models.CharField(blank=True, max_length=500, null=True, verbose_name='游戏卡描述')),
                ('restriction', models.CharField(blank=True, max_length=500, null=True, verbose_name='卡片内容限制')),
                ('note', models.CharField(blank=True, max_length=500, null=True, verbose_name='对卡片的其他说明')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='游戏')),
            ],
        ),
    ]
