# Generated by Django 3.2.12 on 2022-03-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20220303_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='xfile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='游戏卡数据文件'),
        ),
    ]
