# Generated by Django 3.2.12 on 2022-03-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_xfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='card_discriptioin_field',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_name_field',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_note_field',
        ),
        migrations.RemoveField(
            model_name='game',
            name='card_restriction_field',
        ),
        migrations.RemoveField(
            model_name='gamecard',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='gamecard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gamecard',
            name='note',
        ),
        migrations.RemoveField(
            model_name='gamecard',
            name='restriction',
        ),
        migrations.AddField(
            model_name='game',
            name='field_name_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='field_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='field_name_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='field_name_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='field_name_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='field_name_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='field_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='field_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='field_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='field_4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='field_5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gamecard',
            name='field_6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_category', to='games.gamecategory', verbose_name='所属目录'),
        ),
        migrations.AlterField(
            model_name='gamecard',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_card', to='games.game', verbose_name='游戏'),
        ),
        migrations.AlterField(
            model_name='gamecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='games.gamecategory', verbose_name='上级目录'),
        ),
    ]
