# Generated by Django 3.2.12 on 2022-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20220829_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='cfile',
            field=models.ImageField(upload_to='covers', verbose_name='丛书封面'),
        ),
    ]
