# Generated by Django 3.2.12 on 2022-10-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_alter_series_cfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='cfile',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_visible_1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_visible_2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_visible_3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_visible_4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_visible_5',
        ),
        migrations.RemoveField(
            model_name='game',
            name='field_visible_6',
        ),
        migrations.AddField(
            model_name='game',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.series', verbose_name='所属丛书名称'),
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
    ]
