# Generated by Django 3.2.12 on 2022-10-12 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20221012_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_include', to='games.series', verbose_name='所属丛书名称'),
        ),
    ]
